server:
  port: 8080

spring:
  # common
  datasource:
    url: jdbc:h2:mem:maintenance-db;DB_CLOSE_DELAY=-1;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: none
    flyway:
      enabled: false

  application:
    name: coolname

  profiles:
    active: local
    default: local

  banner:
    location: classpath:/banner.txt

  jpa:
    open-in-view: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

springdoc: # http://localhost:8080/misc/swagger-ui/index.html
  api-docs:
    path: /misc/api-docs
    enabled: false
  swagger-ui:
    path: /misc/swagger-ui.html
    enabled: false
    tagsSorter: alpha
    operationsSorter: method

logging:
  level:
    com.zaxxer.hikari: INFO

---

env: DEV

spring:
  config:
    activate:
      on-profile: local


---

env: PROD

spring:
  config:
    activate:
      on-profile: prod
